name = "tesla-model-pi"
main = "src/index.ts"
compatibility_date = "2026-01-02"

# Cloudflare 账户配置
account_id = "1f6ac259e674c8327282b3b97b427b5b"
workers_dev = true

# KV 命名空间配置（注意：免费计划每月提供10万次读取和1万次写入）
[[kv_namespaces]]
binding = "MODEL_PI"
id = "589f4a8040d74c95b11525307ffe48d5"
preview_id = "589f4a8040d74c95b11525307ffe48d5"

# 环境变量
[vars]
ENVIRONMENT = "production"